import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: 24,
    fontFamily:
      'Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji"',
    color: '#0f172a',
  },
  title: { fontSize: 24, fontWeight: 700, marginBottom: 16 },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 },
  card: {
    background: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: 12,
    boxShadow: '0 1px 2px rgba(0,0,0,0.04)',
    padding: 16,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  h2: { fontSize: 18, fontWeight: 600, margin: 0 },
  formRow: { display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' },
  input: {
    flex: '1 1 180px',
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #e5e7eb',
    outline: 'none',
  },
  select: {
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #e5e7eb',
    outline: 'none',
    minWidth: 180,
  },
  buttonPrimary: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #0284c7',
    background: '#0284c7',
    color: '#fff',
    cursor: 'pointer',
  },
  buttonPrimaryDisabled: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid #94a3b8',
    background: '#94a3b8',
    color: '#fff',
    cursor: 'not-allowed',
    opacity: 0.8,
  },
  list: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  listItem: {
    padding: '10px 12px',
    border: '1px solid #e5e7eb',
    borderRadius: 10,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: { color: '#0ea5e9', fontWeight: 600 },
};
